#!/usr/bin/env bash

GsrStatus() {
    if [ ! -f /tmp/gsr-$1 ]; then
        echo "false"
        return 0
    else
        echo "true"
        return 1
    fi
}

StopGsr() {
    kill -SIGINT $(cat /tmp/gsr-$1)
    rm /tmp/gsr-$1
}

StartRecording() {
    rm $XDG_CACHE_HOME/gsr-record.log
    local OUTPUTDIR="$HOME/Videos/Replays/Desktop"
    local SCRIPT_LOCATION="/home/spicy/.local/bin/replay_organizer"
    local DATE=$(date +"%Y-%m-%d_%H:%M:%S")
    gpu-screen-recorder -v no \
        -w "portal" \
        -c "mp4" \
        -bm "cbr" \
        -q "15000" \
        -f "60" \
        -fm "cfr" \
        -k "h264" \
        -ac "opus" \
        -a "default_output" \
        -cr "full" \
        -cursor "yes" \
        -o "$OUTPUTDIR/../../Recordings/Recording_$DATE.mp4" \
        -sc $SCRIPT_LOCATION &> $XDG_CACHE_HOME/gsr-record.log &
    disown

    echo $! >/tmp/gsr-record
}

StartBuffer() {
    rm $XDG_CACHE_HOME/gsr-buffer.log
    local OUTPUTDIR="$HOME/Videos/Replays/Desktop"
    local SCRIPT_LOCATION="/home/spicy/.local/bin/replay_organizer"
    gpu-screen-recorder \
        -v no \
        -w screen \
        -f 60 \
        -bm cbr \
        -q 25000 \
        -c mkv \
        -r 30 \
        -a default_output \
        -ac opus \
        -k hevc \
        -o "$HOME/Videos/Replays/Desktop" \
        -sc $SCRIPT_LOCATION &> $XDG_CACHE_HOME/gsr-buffer.log &
    disown
    echo $! >/tmp/gsr-buffer
}

Notify() {

    case $XDG_CURRENT_DESKTOP in
    KDE)
        qdbus6 org.kde.plasmashell /org/kde/osdService org.kde.osdService.showText "keyframe-record" "$1"
        ;;
    Hyprland)
        qs -c shell ipc call osd osdmsg "$1" "keyframe-record"
        ;;
    *)
        notify-send -h string:x-canonical-private-synchronous:gsr -a "GSR" "GSR" "$1" -u low
        ;;
    esac

}
case $1 in
toggle)
    if GsrStatus "buffer"; then
        StartBuffer
        Notify "GSR started"
    else
        StopGsr "buffer"
        Notify "GSR stopped"
    fi
    ;;
save)
    kill -SIGUSR1 $(cat /tmp/gsr-buffer)
    ;;
record)
    if GsrStatus "record"; then
        StartRecording
        Notify "Recoding started"
    else
        StopGsr "record"
    fi
    ;;
status)
    echo "{\"recording\":$(GsrStatus 'record'),\"buffer\":$(GsrStatus 'buffer')}"
    ;;
*)
    exit 1
    ;;
esac
