#!/usr/bin/env bash
#set -e

#I Know, It's better to check if this dir exits but......
Screenshot_Dir="${XDG_PICTURES_DIR:-$HOME/Pictures}/Screenshots"
DATE=$(date +"%Y-%m-%d_%H:%M:%S")
Screenshot="$Screenshot_Dir/Screenshot_$DATE.jpeg"

send_notification() {

    case $(notify-send -u normal --app-name "تصوير شاشة" "حفظت الصورة" -i "spectacle" --action view-preview="افتح" --action edit-entry-symbolic="عدل" --action delete-symbolic="احذف" --hint STRING:image-path:"$Screenshot") in
    view-preview)
        uwsm app -S both -- xdg-open "$Screenshot" &>/dev/null &
        disown
        ;;
    delete-symbolic)
        rm "$Screenshot"
        ;;
    edit-entry-symbolic)
        uwsm app -S both -- ksnip -e "$Screenshot" &>/dev/null &
        disown
        ;;
    *)
        exit 0
        ;;
    esac
    exit 0
}

function copyScreenshot() {
    wl-copy <"$Screenshot"
}

case $1 in
full)
    grim -c -t jpeg "$Screenshot"
    copyScreenshot
    send_notification
    ;;
region)
    freezeScreen start
    sleep 0.05
    coords="$(slurp -b '#1E263690' -c '#285A77' -w 0)"
    if [ $? -ne 0 ]; then
        exit 0
    else
        grim -t jpeg -g "$coords" "$Screenshot"
        copyScreenshot
        send_notification
    fi
    ;;
*)
    echo "Usage: screenshot
        full: take a full screenshot of the Screenshot
        region: take a screenshot of a selected area"
    ;;
esac
